version: '3.9'
services:
  api:
    build: .
    container_name: moto-clube-api
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/app
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: moto-clube-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
